language: emacs-lisp
env:
  matrix:
    - emacs=emacs25

before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs python npm nodejs git python-pip python-virtualenv golang-go elixir rustc cargo
  - sudo pip install -r requirements.txt
  - sudo npm install -g csslint jshint tern
  - sudo ln -sf /usr/bin/nodejs /usr/bin/node

script:
- make test
