sudo: required

language: emacs-lisp

os:
  - linux
  - osx

services:
  - docker

stages:
  - ubuntu
  - debian
  - arch
  - gentoo
  - osx

jobs:
  include:
    - stage: ubuntu
      script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f docker/ubuntu/Dockerfile .; fi
    - stage: debian
      script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f docker/debian/Dockerfile .; fi
    - stage: arch
      script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f docker/arch/Dockerfile .; fi
    - stage: gentoo
      script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f docker/gentoo/Dockerfile .; fi
    - stage: osx
      script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make osx; fi
