language: emacs-lisp
env:
  matrix:
    - emacs=emacs25

before_install:
  - sudo add-apt-repository -y ppa:adrozdoff/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs

script:
- make test
