sudo: required

language: emacs-lisp

services:
  - docker

script:
  - docker build -f docker/ubuntu/Dockerfile .
  - docker build -f docker/arch/Dockerfile .
  - docker build -f docker/gentoo/Dockerfile .
