sudo: required

services:
  - docker

stages:
  - ubuntu
  - debian
  - arch
  - gentoo

jobs:
  include:
    - stage: ubuntu
      language: emacs-lisp
      script: docker build -f docker/ubuntu/Dockerfile .
    - stage: debian
      language: emacs-lisp
      script: docker build -f docker/debian/Dockerfile .
    - stage: arch
      language: emacs-lisp
      script: docker build -f docker/arch/Dockerfile .
    - stage: gentoo
      language: emacs-lisp
      script: docker build -f docker/gentoo/Dockerfile .
