language: emacs-lisp
env:
  matrix:
    - emacs=emacs25

before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs python git python-pip python-virtualenv
  - sudo pip install -r requirements.txt

script:
- make test
